import type { CustomerPersona } from '@/types/simulation';

export const STANDARD_PERSONAS: CustomerPersona[] = [
  {
    id: 'patient_customer',
    name: 'Sarah - Patient First-Time Buyer',
    description: 'Polite customer asking about delivery status',
    traits: {
      patience: 0.9,
      techSavvy: 0.7,
      assertiveness: 0.3,
      emotionalIntensity: 0.2,
    },
    communicationStyle: 'formal',
    typicalScenarios: ['DELIVERY_STATUS', 'GENERAL_QUESTION'],
    samplePhrases: [
      'Hello, I was wondering if you could help me...',
      'Thank you for looking into this for me',
      'I appreciate your help',
    ],
    expectedResolution: 'AI_RESOLVED',
  },
  {
    id: 'frustrated_delivery',
    name: 'Mike - Frustrated About Late Delivery',
    description: 'Customer whose delivery is overdue and getting increasingly frustrated',
    traits: {
      patience: 0.3,
      techSavvy: 0.5,
      assertiveness: 0.8,
      emotionalIntensity: 0.7,
    },
    communicationStyle: 'direct',
    typicalScenarios: ['DELIVERY_PROBLEM'],
    samplePhrases: [
      'I was promised delivery 3 days ago!',
      'This is unacceptable',
      'I need this sorted TODAY',
    ],
    expectedResolution: 'AI_RESOLVED_WITH_COMPENSATION',
  },
  {
    id: 'elderly_confused',
    name: 'Margaret - Elderly Customer Needing Extra Support',
    description: 'Older customer who needs patient, clear communication',
    traits: {
      patience: 0.8,
      techSavvy: 0.2,
      assertiveness: 0.4,
      emotionalIntensity: 0.5,
    },
    communicationStyle: 'conversational',
    typicalScenarios: ['WARRANTY_QUESTION', 'ADMIN_ISSUE'],
    samplePhrases: [
      'My son helped me find this chat...',
      "I'm not very good with computers",
      'Could you explain that again more simply?',
    ],
    vulnerabilitySignals: ['my son is handling', 'pension', 'retired'],
    expectedResolution: 'ESCALATED_VULNERABLE',
  },
  {
    id: 'missing_accessory',
    name: 'James - Missing Accessory Report',
    description: 'Customer reporting a missing item from their order',
    traits: {
      patience: 0.6,
      techSavvy: 0.8,
      assertiveness: 0.5,
      emotionalIntensity: 0.4,
    },
    communicationStyle: 'factual',
    typicalScenarios: ['MISSING_ITEM'],
    samplePhrases: [
      "The charging cable wasn't in the box",
      'Everything else was there, just not the floor mats',
      'Can you send the missing items?',
    ],
    expectedResolution: 'AI_RESOLVED_RESHIP',
  },
  {
    id: 'refund_seeker_valid',
    name: 'Emma - Valid Small Refund Request',
    description: 'Customer with legitimate small refund request under £100',
    traits: {
      patience: 0.5,
      techSavvy: 0.7,
      assertiveness: 0.6,
      emotionalIntensity: 0.3,
    },
    communicationStyle: 'business',
    typicalScenarios: ['REFUND_REQUEST'],
    samplePhrases: [
      "I'd like a refund for the cleaning kit I never received",
      'The floor mats were damaged, can I get my money back?',
      "I paid extra for accessories that weren't delivered",
    ],
    expectedResolution: 'AI_RESOLVED_REFUND',
    refundAmount: { min: 20, max: 80 },
  },
  {
    id: 'refund_seeker_large',
    name: 'David - Large Refund Request',
    description: 'Customer requesting refund above AI authority limit (£100)',
    traits: {
      patience: 0.4,
      techSavvy: 0.6,
      assertiveness: 0.8,
      emotionalIntensity: 0.6,
    },
    communicationStyle: 'demanding',
    typicalScenarios: ['REFUND_REQUEST'],
    samplePhrases: [
      'I want a £500 refund for this inconvenience',
      'The car had issues so I deserve significant compensation',
      'I expect at least £200 back',
    ],
    expectedResolution: 'ESCALATED_AUTHORITY_LIMIT',
    refundAmount: { min: 150, max: 500 },
  },
  {
    id: 'warranty_query',
    name: 'Thomas - Warranty Coverage Question',
    description: 'Customer asking about what their warranty covers',
    traits: {
      patience: 0.7,
      techSavvy: 0.5,
      assertiveness: 0.4,
      emotionalIntensity: 0.2,
    },
    communicationStyle: 'inquisitive',
    typicalScenarios: ['WARRANTY_QUESTION'],
    samplePhrases: [
      'What does my warranty actually cover?',
      'Is the air conditioning covered under warranty?',
      'My warranty expires soon, what are my options?',
    ],
    expectedResolution: 'AI_RESOLVED_INFO',
  },
  {
    id: 'financial_hardship',
    name: 'Karen - Financial Difficulties',
    description: 'Customer mentioning financial hardship - should trigger vulnerability escalation',
    traits: {
      patience: 0.5,
      techSavvy: 0.4,
      assertiveness: 0.3,
      emotionalIntensity: 0.8,
    },
    communicationStyle: 'emotional',
    typicalScenarios: ['REFUND_REQUEST', 'FINANCE_ISSUE'],
    samplePhrases: [
      "I've just lost my job and really need this refund",
      "I'm struggling financially at the moment",
      "I can't afford to wait for this to be sorted",
    ],
    vulnerabilitySignals: ['lost my job', 'struggling financially', "can't afford", 'benefits'],
    expectedResolution: 'ESCALATED_VULNERABLE',
  },
  {
    id: 'vehicle_defect',
    name: 'Michael - Vehicle Defect Report',
    description: 'Customer reporting a non-safety problem with their vehicle',
    traits: {
      patience: 0.4,
      techSavvy: 0.6,
      assertiveness: 0.7,
      emotionalIntensity: 0.5,
    },
    communicationStyle: 'concerned',
    typicalScenarios: ['VEHICLE_DEFECT', 'WARRANTY_CLAIM'],
    samplePhrases: [
      "There's a strange noise coming from the engine",
      'The dashboard warning light keeps coming on',
      "The car isn't starting properly",
    ],
    expectedResolution: 'AI_RESOLVED_TICKET',
  },
  {
    id: 'safety_concern',
    name: 'Robert - Safety Issue',
    description: 'Customer with serious vehicle safety concern - must escalate',
    traits: {
      patience: 0.2,
      techSavvy: 0.5,
      assertiveness: 0.9,
      emotionalIntensity: 0.9,
    },
    communicationStyle: 'urgent',
    typicalScenarios: ['VEHICLE_DEFECT'],
    samplePhrases: [
      "The brakes feel spongy and I'm worried",
      'The steering wheel is pulling to one side',
      "I think there's something seriously wrong with the car",
    ],
    escalationTriggers: ['brakes', 'steering', 'safety', 'dangerous'],
    expectedResolution: 'ESCALATED_SAFETY',
  },
];
